# Generated by Django 4.2.7 on 2023-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Eid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Sal',
            field=models.IntegerField(),
        ),
    ]
